package backtest

import (
	"errors"
	"time"

	"event-driven-backtesting-engine/internal/domain"
	"event-driven-backtesting-engine/internal/events"
	"event-driven-backtesting-engine/internal/matching"
	"event-driven-backtesting-engine/internal/order"
	"event-driven-backtesting-engine/internal/pipeline"
	"event-driven-backtesting-engine/internal/portfolio"
	"event-driven-backtesting-engine/internal/statistics"
	"event-driven-backtesting-engine/internal/strategy"
)

type RunnerConfig struct {
	RunID        int
	StrategyName string
	Symbol       string
	Timeframe    string
	StartDate    time.Time
	EndDate      time.Time

	InitialCapital float64
}

type Runner struct {
	pipeline pipeline.CandlePipeline

	queue      *events.EventQueue
	dispatcher *events.EventDispatcher

	strategy   *strategy.EmaCross
	order      *order.Manager
	matching   *matching.Engine
	portfolio  *portfolio.Engine
	statistics *statistics.Engine

	repository statistics.BacktestResultRepository

	config RunnerConfig
}

func NewRunner(
	config RunnerConfig,
	candlePipeline pipeline.CandlePipeline,
	repository statistics.BacktestResultRepository,
) (*Runner, error) {

	if candlePipeline == nil {
		return nil, errors.New("candle pipeline is required")
	}

	if repository == nil {
		return nil, errors.New("backtest result repository is required")
	}

	queue := events.NewEventQueue()
	dispatcher := events.NewEventDispatcher()

	// Portfolio
	initialPortfolio := domain.NewPortfolio(
		config.RunID,
		config.InitialCapital,
	)

	portfolioEngine := portfolio.NewEngine(
		queue,
		initialPortfolio,
	)

	// Order Manager
	orderManager := order.NewManager(
		portfolioEngine,
		queue,
	)

	// Matching Engine
	matchingEngine := matching.NewEngine(
		queue,
	)

	// Statistics Engine
	statisticsEngine := statistics.NewEngine()

	statisticsEngine.SetRepository(repository)

	// Strategy
	emaCross := strategy.NewEmaCross(
		9,
		21,
	)

	emaCross.SetDispatcher(dispatcher)
	emaCross.SetRunID(config.RunID)

	if err := emaCross.Initialize(); err != nil {
		return nil, err
	}

	runner := &Runner{
		pipeline:   candlePipeline,
		queue:      queue,
		dispatcher: dispatcher,
		strategy:   emaCross,
		order:      orderManager,
		matching:   matchingEngine,
		portfolio:  portfolioEngine,
		statistics: statisticsEngine,
		repository: repository,
		config:     config,
	}

	runner.registerHandlers()

	return runner, nil
}

func (r *Runner) registerHandlers() {
	r.dispatcher.Register(
		events.SignalGeneratedEventType,
		r.order.Consume,
	)

	r.dispatcher.Register(
		events.OrderCreatedEventType,
		r.matching.Consume,
	)

	r.dispatcher.Register(
		events.TradeExecutedEventType,
		r.portfolio.Consume,
	)

	r.dispatcher.Register(
		events.TradeExecutedEventType,
		r.statistics.Consume,
	)

	r.dispatcher.Register(
		events.PortfolioUpdatedEventType,
		r.statistics.Consume,
	)

	r.dispatcher.Register(
		events.BacktestCompletedEventType,
		r.statistics.Consume,
	)
}

func (r *Runner) processQueue() error {
	for !r.queue.IsEmpty() {
		event, ok := r.queue.Pop()

		if !ok {
			continue
		}

		if err := r.dispatcher.Dispatch(event); err != nil {
			return err
		}
	}

	return nil
}

func (r *Runner) Run() (statistics.BacktestResult, error) {
	for {
		candle, ok, err := r.pipeline.Next()
		if err != nil {
			return statistics.BacktestResult{}, err
		}

		if !ok {
			break
		}

		// Candle → Strategy
		r.strategy.OnData(candle)

		// Process events generated by Strategy
		if err := r.processQueue(); err != nil {
			return statistics.BacktestResult{}, err
		}

		// Update portfolio valuation using current market price.
		r.portfolio.UpdateMarketPrices(candle)

		// Process PortfolioUpdatedEvent.
		if err := r.processQueue(); err != nil {
			return statistics.BacktestResult{}, err
		}
	}

	// Build final backtest result.
	result := r.buildResult()

	// Phase 10.8:
	// Publish BacktestCompletedEvent.
	completedEvent := r.buildCompletedEvent(result)

	if err := r.dispatcher.Dispatch(completedEvent); err != nil {
		return statistics.BacktestResult{}, err
	}

	return result, nil
}

func (r *Runner) buildResult() statistics.BacktestResult {
	performance := r.statistics.Performance()

	equityCurve := r.statistics.EquityCurve()

	return statistics.BacktestResult{
		RunID:        r.config.RunID,
		StrategyName: r.config.StrategyName,
		Symbol:       r.config.Symbol,
		Timeframe:    r.config.Timeframe,

		StartDate: r.config.StartDate,
		EndDate:   r.config.EndDate,

		TotalReturn: statistics.TotalReturn(equityCurve),
		WinRate:     performance.WinRate,
		SharpeRatio: performance.SharpeRatio,
		MaxDrawdown: performance.MaxDrawdown,
	}
}

func (r *Runner) buildCompletedEvent(
	result statistics.BacktestResult,
) events.BacktestCompletedEvent {
	return events.NewBacktestCompletedEvent(
		result.RunID,
		result.StrategyName,
		result.Symbol,
		result.Timeframe,
		result.StartDate,
		result.EndDate,
		result.TotalReturn,
		result.WinRate,
		result.SharpeRatio,
		result.MaxDrawdown,
	)
}
